language: node_js

node_js:
    - 9

sudo: false

cache: yarn

script:
    - npm run test

after_success:
    - ./dev/release.sh

after_failure:
    - cat npm-debug.log

env:
    global:
        # GITHUP TOKEN
        - secure: "Zy6YCBtBtjOvEw67L9wWtDjo6NmrTKgLSouTg89T0I2awBB0SocQn8jEy6OHqvnap7LgEHHQF5xKeIp9yVotgoiJ+bgn5NRGgujiTwuxMFMeRpR3BGDbBjf29jgfbqSFywMM0b1uAgoMUz0gGpJIrPXOBT+6Y2pyUYurd7Dbnvk="
